# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_oc_routers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_oc_routers

  target 'ios_oc_routersTests' do
    inherit! :search_paths
    # Pods for testing
 pod 'Bifrost', '~> 1.0.0'
  end

  target 'ios_oc_routersUITests' do
    # Pods for testing
  end

end
